[package]
name = "chip8_emu"
version = "0.1.0"
authors = ["shellbear <shellbear@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
